### ISSUE TITLE
Internal server error after upgrading to KeyCloak v23.0.1

### ISSUE THREAD

**Issue by jwesselink** [klausbetz/apple-identity-provider-keycloak#60] opened 2023-12-02 11:14 UTC
After upgrading from v22.0.5 to v23.0.1, I get an Internal server error after being redirected back to KeyCloak.

I'm not seeing any error logs in the console logging.

Is there anything I can do to get more info to help you?

**Comment by klausbetz** [comment] 2023-12-06 14:53
Hi @jwesselink,

I'm sorry for responding that late.
I'll try to reproduce it on my setup.

Just for clarification: Your setup worked fine with `v22.0.5`?

**Comment by kotofey-da-powah** [comment] 2023-12-20 11:25
Problem seems to be resolved with `v23.0.3` and `1.8.0`. Can you double-check this on your setup?

**Comment by klausbetz** [comment] 2023-12-20 17:20
Tested using `1.8.0` and Keycloak `v23.0.0`, `v23.0.2` and `v23.0.3`.
Unfortunately, all versions of Keycloak behave the same. :/

**Comment by jwesselink** [comment] 2023-12-23 09:58
v23.0.3 and 1.8.0 still fails with internal server error after being redirect back

**Comment by klausbetz** [comment] 2023-12-24 11:51
@jwesselink: Thank you for investigating and fixing this issue!
You just made this extension better than it was before 🙇 

Please check out [1.9.0](https://github.com/klausbetz/apple-identity-provider-keycloak/releases/tag/1.9.0).

**Closed by klausbetz** 2023-12-24 11:51 UTC
